server:
  port: ${PORT:8080}
spring:
  profiles:
    active: prod
  sendgrid:
    proxy:
      host: smtp.sendgrid.net
      port: 465
sendgrid:
  template-cadastro-id: d-eb72f72bb13f46dfb618b9ffbcc0eee1
  template-recupera-senha-id: d-d0d45c85bfef45ed8c1744e718a408a3
fcm:
  service-account-file: /resources/sagi-22525-firebase-adminsdk-57y5t-87df904db0.json