spring:
  profiles: prod
  environment: production
  datasource:
    platform: mariadb
    url: jdbc:mariadb:failover//45.62.230.34/sagi_inventario
    username: root
    password: master@root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
app:
  url: https://sagi-inventario.herokuapp.com