spring:
  profiles: dev
  environment: development
  datasource:
    url: jdbc:mysql://localhost:3306/sagi_inventario?useSSL=false&useTimezone=true&serverTimezone=America/Bahia&allowPublicKeyRetrieval=true
    username: root
    password: eloah1106
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
app:
  url: http://localhost:${server.port}/